/* N등급 공용 꽃 마스터 데이터 - page2/page5 공동 사용 */
window.FLOWER_MASTER_DATA = [
  {
    "id": "F0260",
    "name": "붉은 장미",
    "listName": "[레벨 01 해제] 붉은 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0260.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0260.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 01 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0261",
    "name": "은방울꽃",
    "listName": "[레벨 01 해제] 은방울꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0261.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0261.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 01 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0262",
    "name": "자색 도라지",
    "listName": "[레벨 03 해제] 자색 도라지",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0262.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0262.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 03 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0263",
    "name": "노란 장미",
    "listName": "[레벨 04 해제] 노란 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0263.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0263.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 04 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0264",
    "name": "카네이션",
    "listName": "[레벨 05 해제] 카네이션",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0264.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0264.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 05 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0265",
    "name": "노란 튤립",
    "listName": "[레벨 06 해제] 노란 튤립",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0265.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0265.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 06 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0266",
    "name": "제비꽃",
    "listName": "[레벨 07 해제] 제비꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0266.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0266.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 07 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0267",
    "name": "분홍 튤립",
    "listName": "[레벨 08 해제] 분홍 튤립",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0267.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0267.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 08 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0268",
    "name": "호접란",
    "listName": "[레벨 09 해제] 호접란",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0268.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0268.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 09 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0269",
    "name": "분홍 장미",
    "listName": "[레벨 10 해제] 분홍 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0269.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0269.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 10 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0270",
    "name": "흰 백합",
    "listName": "[레벨 11 해제] 흰 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0270.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0270.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 11 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0271",
    "name": "데이지",
    "listName": "[레벨 12 해제] 데이지",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0271.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0271.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 12 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0272",
    "name": "분홍 백합",
    "listName": "[레벨 13 해제] 분홍 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0272.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0272.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 13 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0273",
    "name": "푸른별꽃",
    "listName": "[레벨 14 해제] 푸른별꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0273.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0273.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 14 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0274",
    "name": "노란 백합",
    "listName": "[레벨 15 해제] 노란 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0274.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0274.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 15 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0275",
    "name": "자색 수국",
    "listName": "[레벨 16 해제] 자색 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0275.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0275.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 16 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0276",
    "name": "동백꽃",
    "listName": "[레벨 17 해제] 동백꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0276.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0276.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 17 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0277",
    "name": "분홍 수국",
    "listName": "[레벨 18 해제] 분홍 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0277.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0277.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 18 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0278",
    "name": "구즈마니아",
    "listName": "[레벨 19 해제] 구즈마니아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0278.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0278.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 19 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0279",
    "name": "파란 수국",
    "listName": "[레벨 20 해제] 파란 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0279.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0279.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 20 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0280",
    "name": "해바라기",
    "listName": "[레벨 21 해제] 해바라기",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0280.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0280.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 21 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0281",
    "name": "프리지아",
    "listName": "[레벨 22 해제] 프리지아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0281.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0281.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 22 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0282",
    "name": "금술 국화",
    "listName": "[레벨 23 해제] 금술 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0282.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0282.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 23 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0283",
    "name": "수선화",
    "listName": "[레벨 24 해제] 수선화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0283.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0283.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 24 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0284",
    "name": "거베라",
    "listName": "[레벨 25 해제] 거베라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0284.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0284.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 25 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0285",
    "name": "붉은 카라",
    "listName": "[레벨 26 해제] 붉은 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0285.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0285.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 26 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0286",
    "name": "초롱꽃",
    "listName": "[레벨 27 해제] 초롱꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0286.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0286.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 27 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0287",
    "name": "노란 카라",
    "listName": "[레벨 28 해제] 노란 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0287.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0287.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 28 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0288",
    "name": "민들레",
    "listName": "[레벨 29 해제] 민들레",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0288.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0288.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 29 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0289",
    "name": "자색 카라",
    "listName": "[레벨 30 해제] 자색 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0289.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0289.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 30 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0290",
    "name": "연보라 히아신스",
    "listName": "[레벨 31 해제] 연보라 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0290.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0290.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 31 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0291",
    "name": "자귀나무꽃",
    "listName": "[레벨 32 해제] 자귀나무꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0291.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0291.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 32 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0292",
    "name": "연분홍 히아신스",
    "listName": "[레벨 33 해제] 연분홍 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0292.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0292.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 33 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0293",
    "name": "재스민",
    "listName": "[레벨 34 해제] 재스민",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0293.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0293.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 34 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0294",
    "name": "연노랑 히아신스",
    "listName": "[레벨 35 해제] 연노랑 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0294.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0294.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 35 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0295",
    "name": "황금 여의 국화",
    "listName": "[레벨 36 해제] 황금 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0295.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0295.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 36 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0296",
    "name": "치자꽃",
    "listName": "[레벨 37 해제] 치자꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0296.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0296.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 37 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0297",
    "name": "연분홍 여의 국화",
    "listName": "[레벨 38 해제] 연분홍 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0297.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0297.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 38 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0298",
    "name": "분홍 복사꽃",
    "listName": "[레벨 39 해제] 분홍 복사꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0298.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0298.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 39 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0299",
    "name": "연귤색 여의 국화",
    "listName": "[레벨 40 해제] 연귤색 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0299.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0299.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 40 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0300",
    "name": "비취 리시안셔스",
    "listName": "[레벨 41 해제] 비취 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0300.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0300.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 41 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0301",
    "name": "자운 라일락",
    "listName": "[레벨 42 해제] 자운 라일락",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0301.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0301.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 42 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0302",
    "name": "붉은구름 리시안셔스",
    "listName": "[레벨 43 해제] 붉은구름 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0302.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0302.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 43 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0303",
    "name": "연노랑 라일락",
    "listName": "[레벨 44 해제] 연노랑 라일락",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0303.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0303.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 44 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0304",
    "name": "호박 리시안셔스",
    "listName": "[레벨 45 해제] 호박 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0304.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0304.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 45 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0305",
    "name": "자홍색 부겐빌레아",
    "listName": "[레벨 46 해제] 자홍색 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0305.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0305.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 46 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0306",
    "name": "물망초",
    "listName": "[레벨 47 해제] 물망초",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0306.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0306.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 47 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0307",
    "name": "연노랑 부겐빌레아",
    "listName": "[레벨 48 해제] 연노랑 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0307.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0307.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 48 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0308",
    "name": "설흔 구리향",
    "listName": "[레벨 49 해제] 설흔 구리향",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0308.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0308.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 49 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0309",
    "name": "연벚꽃 부겐빌레아",
    "listName": "[레벨 50 해제] 연벚꽃 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0309.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0309.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 50 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0310",
    "name": "탐스러운 덩굴장미",
    "listName": "[레벨 51 해제] 탐스러운 덩굴장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0310.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0310.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 51 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0311",
    "name": "성심 백합",
    "listName": "[레벨 52 해제] 성심 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0311.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0311.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 52 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0312",
    "name": "자색 폭스테일",
    "listName": "[레벨 53 해제] 자색 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0312.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0312.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 53 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0313",
    "name": "서리꽃 석곡",
    "listName": "[레벨 54 해제] 서리꽃 석곡",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0313.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0313.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 54 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0314",
    "name": "분홍색 폭스테일",
    "listName": "[레벨 55 해제] 분홍색 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0314.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0314.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 55 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0315",
    "name": "청백 로벨리아",
    "listName": "[레벨 56 해제] 청백 로벨리아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0315.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0315.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 56 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0316",
    "name": "노란 폭스테일",
    "listName": "[레벨 57 해제] 노란 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0316.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0316.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 57 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0317",
    "name": "자색 괭이밥",
    "listName": "[레벨 58 해제] 자색 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0317.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0317.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 58 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0318",
    "name": "주황색 괭이밥",
    "listName": "[레벨 59 해제] 주황색 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0318.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0318.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 59 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0319",
    "name": "빛나는 노란 괭이밥",
    "listName": "[레벨 60 해제] 빛나는 노란 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0319.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0319.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 60 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0320",
    "name": "눈꽃 용토주",
    "listName": "[레벨 61 해제] 눈꽃 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0320.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0320.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 61 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0321",
    "name": "금잔 금관화",
    "listName": "[레벨 62 해제] 금잔 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0321.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0321.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 62 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0322",
    "name": "안개 분홍 신부화",
    "listName": "[레벨 63 해제] 안개 분홍 신부화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0322.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0322.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 63 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0323",
    "name": "진홍 벚꽃 용토주",
    "listName": "[레벨 64 해제] 진홍 벚꽃 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0323.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0323.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 64 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0324",
    "name": "주황 불꽃 금관화",
    "listName": "[레벨 65 해제] 주황 불꽃 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0324.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0324.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 65 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0325",
    "name": "구름 베일 신부화",
    "listName": "[레벨 66 해제] 구름 베일 신부화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0325.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0325.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 66 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0326",
    "name": "보랏빛 베일 용토주",
    "listName": "[레벨 67 해제] 보랏빛 베일 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0326.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0326.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 67 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0327",
    "name": "진홍 불꽃 금관화",
    "listName": "[레벨 68 해제] 진홍 불꽃 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0327.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0327.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 68 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0328",
    "name": "노을빛 신부꽃",
    "listName": "[레벨 69 해제] 노을빛 신부꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0328.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0328.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 69 해제",
    "note": "🎫 무과금 가능"
  }
];
