/* N등급 공용 꽃 마스터 데이터 - page2/page5 공동 사용 */
window.FLOWER_MASTER_DATA = [
  {
    "id": "F0260",
    "name": "붉은 장미",
    "listName": "[레벨 01 해제] 붉은 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0260.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0260.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 01 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0261",
    "name": "은방울꽃",
    "listName": "[레벨 01 해제] 은방울꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0261.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0261.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 01 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0262",
    "name": "자색 도라지",
    "listName": "[레벨 03 해제] 자색 도라지",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0262.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0262.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 03 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0263",
    "name": "노란 장미",
    "listName": "[레벨 04 해제] 노란 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0263.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0263.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 04 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0264",
    "name": "카네이션",
    "listName": "[레벨 05 해제] 카네이션",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0264.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0264.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 05 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0265",
    "name": "노란 튤립",
    "listName": "[레벨 06 해제] 노란 튤립",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0265.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0265.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 06 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0266",
    "name": "제비꽃",
    "listName": "[레벨 07 해제] 제비꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0266.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0266.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 07 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0267",
    "name": "분홍 튤립",
    "listName": "[레벨 08 해제] 분홍 튤립",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0267.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0267.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 08 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0268",
    "name": "호접란",
    "listName": "[레벨 09 해제] 호접란",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0268.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0268.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 09 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0269",
    "name": "분홍 장미",
    "listName": "[레벨 10 해제] 분홍 장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0269.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0269.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 10 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0270",
    "name": "흰 백합",
    "listName": "[레벨 11 해제] 흰 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0270.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0270.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 11 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0271",
    "name": "데이지",
    "listName": "[레벨 12 해제] 데이지",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0271.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0271.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 12 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0272",
    "name": "분홍 백합",
    "listName": "[레벨 13 해제] 분홍 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0272.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0272.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 13 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0273",
    "name": "푸른별꽃",
    "listName": "[레벨 14 해제] 푸른별꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0273.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0273.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 14 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0274",
    "name": "노란 백합",
    "listName": "[레벨 15 해제] 노란 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0274.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0274.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 15 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0275",
    "name": "자색 수국",
    "listName": "[레벨 16 해제] 자색 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0275.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0275.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 16 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0276",
    "name": "동백꽃",
    "listName": "[레벨 17 해제] 동백꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0276.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0276.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 17 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0277",
    "name": "분홍 수국",
    "listName": "[레벨 18 해제] 분홍 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0277.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0277.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 18 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0278",
    "name": "구즈마니아",
    "listName": "[레벨 19 해제] 구즈마니아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0278.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0278.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 19 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0279",
    "name": "파란 수국",
    "listName": "[레벨 20 해제] 파란 수국",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0279.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0279.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 20 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0280",
    "name": "해바라기",
    "listName": "[레벨 21 해제] 해바라기",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0280.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0280.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 21 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0281",
    "name": "프리지아",
    "listName": "[레벨 22 해제] 프리지아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0281.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0281.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 22 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0282",
    "name": "금술 국화",
    "listName": "[레벨 23 해제] 금술 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0282.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0282.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 23 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0283",
    "name": "수선화",
    "listName": "[레벨 24 해제] 수선화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0283.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0283.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 24 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0284",
    "name": "거베라",
    "listName": "[레벨 25 해제] 거베라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0284.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0284.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 25 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0285",
    "name": "붉은 카라",
    "listName": "[레벨 26 해제] 붉은 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0285.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0285.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 26 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0286",
    "name": "초롱꽃",
    "listName": "[레벨 27 해제] 초롱꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0286.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0286.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 27 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0287",
    "name": "노란 카라",
    "listName": "[레벨 28 해제] 노란 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0287.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0287.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 28 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0288",
    "name": "민들레",
    "listName": "[레벨 29 해제] 민들레",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0288.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0288.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 29 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0289",
    "name": "자색 카라",
    "listName": "[레벨 30 해제] 자색 카라",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0289.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0289.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 30 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0290",
    "name": "연보라 히아신스",
    "listName": "[레벨 31 해제] 연보라 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0290.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0290.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 31 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0291",
    "name": "자귀나무꽃",
    "listName": "[레벨 32 해제] 자귀나무꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0291.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0291.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 32 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0292",
    "name": "연분홍 히아신스",
    "listName": "[레벨 33 해제] 연분홍 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0292.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0292.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 33 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0293",
    "name": "재스민",
    "listName": "[레벨 34 해제] 재스민",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0293.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0293.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 34 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0294",
    "name": "연노랑 히아신스",
    "listName": "[레벨 35 해제] 연노랑 히아신스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0294.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0294.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 35 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0295",
    "name": "황금 여의 국화",
    "listName": "[레벨 36 해제] 황금 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0295.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0295.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 36 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0296",
    "name": "치자꽃",
    "listName": "[레벨 37 해제] 치자꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0296.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0296.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 37 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0297",
    "name": "연분홍 여의 국화",
    "listName": "[레벨 38 해제] 연분홍 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0297.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0297.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 38 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0298",
    "name": "분홍 복사꽃",
    "listName": "[레벨 39 해제] 분홍 복사꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0298.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0298.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 39 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0299",
    "name": "연귤색 여의 국화",
    "listName": "[레벨 40 해제] 연귤색 여의 국화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0299.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0299.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 40 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0300",
    "name": "비취 리시안셔스",
    "listName": "[레벨 41 해제] 비취 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0300.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0300.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 41 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0301",
    "name": "자운 라일락",
    "listName": "[레벨 42 해제] 자운 라일락",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0301.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0301.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 42 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0302",
    "name": "붉은구름 리시안셔스",
    "listName": "[레벨 43 해제] 붉은구름 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0302.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0302.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 43 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0303",
    "name": "연노랑 라일락",
    "listName": "[레벨 44 해제] 연노랑 라일락",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0303.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0303.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 44 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0304",
    "name": "호박 리시안셔스",
    "listName": "[레벨 45 해제] 호박 리시안셔스",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0304.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0304.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 45 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0305",
    "name": "자홍색 부겐빌레아",
    "listName": "[레벨 46 해제] 자홍색 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0305.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0305.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 46 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0306",
    "name": "물망초",
    "listName": "[레벨 47 해제] 물망초",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0306.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0306.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 47 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0307",
    "name": "연노랑 부겐빌레아",
    "listName": "[레벨 48 해제] 연노랑 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0307.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0307.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 48 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0308",
    "name": "설흔 구리향",
    "listName": "[레벨 49 해제] 설흔 구리향",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0308.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0308.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 49 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0309",
    "name": "연벚꽃 부겐빌레아",
    "listName": "[레벨 50 해제] 연벚꽃 부겐빌레아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0309.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0309.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 50 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0310",
    "name": "탐스러운 덩굴장미",
    "listName": "[레벨 51 해제] 탐스러운 덩굴장미",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0310.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0310.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 51 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0311",
    "name": "성심 백합",
    "listName": "[레벨 52 해제] 성심 백합",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0311.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0311.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 52 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0312",
    "name": "자색 폭스테일",
    "listName": "[레벨 53 해제] 자색 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0312.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0312.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 53 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0313",
    "name": "서리꽃 석곡",
    "listName": "[레벨 54 해제] 서리꽃 석곡",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0313.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0313.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 54 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0314",
    "name": "분홍색 폭스테일",
    "listName": "[레벨 55 해제] 분홍색 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0314.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0314.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 55 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0315",
    "name": "청백 로벨리아",
    "listName": "[레벨 56 해제] 청백 로벨리아",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0315.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0315.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 56 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0316",
    "name": "노란 폭스테일",
    "listName": "[레벨 57 해제] 노란 폭스테일",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0316.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0316.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 57 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0317",
    "name": "자색 괭이밥",
    "listName": "[레벨 58 해제] 자색 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0317.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0317.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 58 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0318",
    "name": "주황색 괭이밥",
    "listName": "[레벨 59 해제] 주황색 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0318.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0318.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 59 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0319",
    "name": "빛나는 노란 괭이밥",
    "listName": "[레벨 60 해제] 빛나는 노란 괭이밥",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0319.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0319.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 60 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0320",
    "name": "눈꽃 용토주",
    "listName": "[레벨 61 해제] 눈꽃 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0320.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0320.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 61 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0321",
    "name": "금잔 금관화",
    "listName": "[레벨 62 해제] 금잔 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0321.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0321.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 62 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0322",
    "name": "안개 분홍 신부화",
    "listName": "[레벨 63 해제] 안개 분홍 신부화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0322.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0322.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 63 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0323",
    "name": "진홍 벚꽃 용토주",
    "listName": "[레벨 64 해제] 진홍 벚꽃 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0323.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0323.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 64 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0324",
    "name": "주황 불꽃 금관화",
    "listName": "[레벨 65 해제] 주황 불꽃 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0324.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0324.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 65 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0325",
    "name": "구름 베일 신부화",
    "listName": "[레벨 66 해제] 구름 베일 신부화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0325.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0325.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 66 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0326",
    "name": "보랏빛 베일 용토주",
    "listName": "[레벨 67 해제] 보랏빛 베일 용토주",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0326.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0326.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 67 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0327",
    "name": "진홍 불꽃 금관화",
    "listName": "[레벨 68 해제] 진홍 불꽃 금관화",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0327.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0327.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 68 해제",
    "note": "🎫 무과금 가능"
  },
  {
    "id": "F0328",
    "name": "노을빛 신부꽃",
    "listName": "[레벨 69 해제] 노을빛 신부꽃",
    "grade": "N",
    "guildScore": 9,
    "image": "images/flowers/F0328.webp",
    "imageRemote": "https://thecozybook.pages.dev/images/F0328.webp",
    "acquire": "기본 획득 · 획득 가능",
    "unlock": "레벨 69 해제",
    "note": "🎫 무과금 가능"
  },
{
    "id": "R_DEMO_001",
    "name": "야자수 그늘",
    "listName": "[구름이 머무는 얕은 해변] 야자수 그늘",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0236.webp",
    "imageRemote": "https://dorazy.art/images/F0236.webp",
    "acquire": "이벤트 종료",
    "unlock": "구름이 머무는 얕은 해변",
    "note": "구름이 머무는 얕은 해변",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_002",
    "name": "개상사화",
    "listName": "[꽃시장 교환] 개상사화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0190.webp",
    "imageRemote": "https://dorazy.art/images/F0190.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_003",
    "name": "구름빛 델피니움",
    "listName": "[꽃시장 교환] 구름빛 델피니움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0191.webp",
    "imageRemote": "https://dorazy.art/images/F0191.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 1680 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_004",
    "name": "귤빛 불꽃 시클라멘",
    "listName": "[꽃시장 교환] 귤빛 불꽃 시클라멘",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0334.webp",
    "imageRemote": "https://dorazy.art/images/F0334.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_005",
    "name": "그윽한 보랏빛 델피니움",
    "listName": "[꽃시장 교환] 그윽한 보랏빛 델피니움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0193.webp",
    "imageRemote": "https://dorazy.art/images/F0193.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 18 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_006",
    "name": "금박 베고니아",
    "listName": "[꽃시장 교환] 금박 베고니아",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0195.webp",
    "imageRemote": "https://dorazy.art/images/F0195.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_007",
    "name": "금살구 진달래",
    "listName": "[꽃시장 교환] 금살구 진달래",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0197.webp",
    "imageRemote": "https://dorazy.art/images/F0197.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_008",
    "name": "금술 접시꽃",
    "listName": "[꽃시장 교환] 금술 접시꽃",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0199.webp",
    "imageRemote": "https://dorazy.art/images/F0199.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 28 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_009",
    "name": "다투라",
    "listName": "[꽃시장 교환] 다투라",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0203.webp",
    "imageRemote": "https://dorazy.art/images/F0203.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_010",
    "name": "반쯤 핀 칼랑코에",
    "listName": "[꽃시장 교환] 반쯤 핀 칼랑코에",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0209.webp",
    "imageRemote": "https://dorazy.art/images/F0209.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_011",
    "name": "보라솜털 시클라멘",
    "listName": "[꽃시장 교환] 보라솜털 시클라멘",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0333.webp",
    "imageRemote": "https://dorazy.art/images/F0333.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_012",
    "name": "보랏빛 아부틸론",
    "listName": "[꽃시장 교환] 보랏빛 아부틸론",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0213.webp",
    "imageRemote": "https://dorazy.art/images/F0213.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_013",
    "name": "복숭아빛 노루오줌",
    "listName": "[꽃시장 교환] 복숭아빛 노루오줌",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0214.webp",
    "imageRemote": "https://dorazy.art/images/F0214.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_014",
    "name": "복숭아빛 델피니움",
    "listName": "[꽃시장 교환] 복숭아빛 델피니움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0215.webp",
    "imageRemote": "https://dorazy.art/images/F0215.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_015",
    "name": "분홍솜털 안개꽃",
    "listName": "[꽃시장 교환] 분홍솜털 안개꽃",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0220.webp",
    "imageRemote": "https://dorazy.art/images/F0220.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃자수 시간 · 🎫 무과금 가능 / 꽃티켓 2880",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_016",
    "name": "붉은 노을 아부틸론",
    "listName": "[꽃시장 교환] 붉은 노을 아부틸론",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0221.webp",
    "imageRemote": "https://dorazy.art/images/F0221.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 58 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_017",
    "name": "비취잎 소철",
    "listName": "[꽃시장 교환] 비취잎 소철",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0223.webp",
    "imageRemote": "https://dorazy.art/images/F0223.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_018",
    "name": "석산",
    "listName": "[꽃시장 교환] 석산",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0224.webp",
    "imageRemote": "https://dorazy.art/images/F0224.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_019",
    "name": "아리따운 진달래",
    "listName": "[꽃시장 교환] 아리따운 진달래",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0232.webp",
    "imageRemote": "https://dorazy.art/images/F0232.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_020",
    "name": "안개 자색 아프리칸바이올렛",
    "listName": "[꽃시장 교환] 안개 자색 아프리칸바이올렛",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0233.webp",
    "imageRemote": "https://dorazy.art/images/F0233.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_021",
    "name": "연분홍 아프리칸바이올렛",
    "listName": "[꽃시장 교환] 연분홍 아프리칸바이올렛",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0241.webp",
    "imageRemote": "https://dorazy.art/images/F0241.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_022",
    "name": "연분홍 협죽도",
    "listName": "[꽃시장 교환] 연분홍 협죽도",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0243.webp",
    "imageRemote": "https://dorazy.art/images/F0243.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_023",
    "name": "연지 아프리칸바이올렛",
    "listName": "[꽃시장 교환] 연지 아프리칸바이올렛",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0244.webp",
    "imageRemote": "https://dorazy.art/images/F0244.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_024",
    "name": "자홍색 협죽도",
    "listName": "[꽃시장 교환] 자홍색 협죽도",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0247.webp",
    "imageRemote": "https://dorazy.art/images/F0247.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_025",
    "name": "진홍빛 아부틸론",
    "listName": "[꽃시장 교환] 진홍빛 아부틸론",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0249.webp",
    "imageRemote": "https://dorazy.art/images/F0249.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 1680 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_026",
    "name": "촉영 해당화",
    "listName": "[꽃시장 교환] 촉영 해당화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0251.webp",
    "imageRemote": "https://dorazy.art/images/F0251.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_027",
    "name": "취한뺨 해당화",
    "listName": "[꽃시장 교환] 취한뺨 해당화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0252.webp",
    "imageRemote": "https://dorazy.art/images/F0252.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 3880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_028",
    "name": "파란 눈의 영광",
    "listName": "[꽃시장 교환] 파란 눈의 영광",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0336.webp",
    "imageRemote": "https://dorazy.art/images/F0336.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_029",
    "name": "핑크 심비디움",
    "listName": "[꽃시장 교환] 핑크 심비디움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0254.webp",
    "imageRemote": "https://dorazy.art/images/F0254.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_030",
    "name": "하늘빛 재클린",
    "listName": "[꽃시장 교환] 하늘빛 재클린",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0255.webp",
    "imageRemote": "https://dorazy.art/images/F0255.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_031",
    "name": "하얀 눈의 영광",
    "listName": "[꽃시장 교환] 하얀 눈의 영광",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0335.webp",
    "imageRemote": "https://dorazy.art/images/F0335.webp",
    "acquire": "꽃시장",
    "unlock": "꽃시장 교환",
    "note": "꽃티켓 2880 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_032",
    "name": "개나리",
    "listName": "[꽃시장 현상금] 개나리",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0189.webp",
    "imageRemote": "https://dorazy.art/images/F0189.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_033",
    "name": "극락조화",
    "listName": "[꽃시장 현상금] 극락조화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0194.webp",
    "imageRemote": "https://dorazy.art/images/F0194.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_034",
    "name": "금살구 페튜니아",
    "listName": "[꽃시장 현상금] 금살구 페튜니아",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0198.webp",
    "imageRemote": "https://dorazy.art/images/F0198.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_035",
    "name": "라이트 클레마티스",
    "listName": "[꽃시장 현상금] 라이트 클레마티스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0205.webp",
    "imageRemote": "https://dorazy.art/images/F0205.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_036",
    "name": "수정빛 페튜니아",
    "listName": "[꽃시장 현상금] 수정빛 페튜니아",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0227.webp",
    "imageRemote": "https://dorazy.art/images/F0227.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_037",
    "name": "순백 폼폼 국화",
    "listName": "[꽃시장 현상금] 순백 폼폼 국화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0229.webp",
    "imageRemote": "https://dorazy.art/images/F0229.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_038",
    "name": "스파티필룸",
    "listName": "[꽃시장 현상금] 스파티필룸",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0231.webp",
    "imageRemote": "https://dorazy.art/images/F0231.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_039",
    "name": "안스리움",
    "listName": "[꽃시장 현상금] 안스리움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0234.webp",
    "imageRemote": "https://dorazy.art/images/F0234.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_040",
    "name": "연귤색 폼폼 국화",
    "listName": "[꽃시장 현상금] 연귤색 폼폼 국화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0237.webp",
    "imageRemote": "https://dorazy.art/images/F0237.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_041",
    "name": "연분홍 폼폼 국화",
    "listName": "[꽃시장 현상금] 연분홍 폼폼 국화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0242.webp",
    "imageRemote": "https://dorazy.art/images/F0242.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_042",
    "name": "향수 백합",
    "listName": "[꽃시장 현상금] 향수 백합",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0257.webp",
    "imageRemote": "https://dorazy.art/images/F0257.webp",
    "acquire": "기본 획득",
    "unlock": "꽃시장 현상금",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_043",
    "name": "먹물색 노루귀",
    "listName": "[꽃의 밀령] 먹물색 노루귀",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0207.webp",
    "imageRemote": "https://dorazy.art/images/F0207.webp",
    "acquire": "이벤트 종료",
    "unlock": "꽃의 밀령",
    "note": "현금 7500원",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_044",
    "name": "보라 심장 물상추",
    "listName": "[꽃의 밀령] 보라 심장 물상추",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0212.webp",
    "imageRemote": "https://dorazy.art/images/F0212.webp",
    "acquire": "이벤트 종료",
    "unlock": "꽃의 밀령",
    "note": "현금 7500원",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_045",
    "name": "복숭아빛 재클린",
    "listName": "[꽃의 밀령] 복숭아빛 재클린",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0216.webp",
    "imageRemote": "https://dorazy.art/images/F0216.webp",
    "acquire": "꽃의 밀령",
    "unlock": "꽃의 밀령",
    "note": "옛날 백화점 · 현금 7500원",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_046",
    "name": "연보라 깃털초",
    "listName": "[꽃의 밀령] 연보라 깃털초",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0239.webp",
    "imageRemote": "https://dorazy.art/images/F0239.webp",
    "acquire": "이벤트 종료",
    "unlock": "꽃의 밀령",
    "note": "2026.07.26 ~ 2026.8.22 · 이벤트보상 7500",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_047",
    "name": "붉은 심장 물상추",
    "listName": "[꽃의 향기 조향] 붉은 심장 물상추",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0222.webp",
    "imageRemote": "https://dorazy.art/images/F0222.webp",
    "acquire": "이벤트 종료",
    "unlock": "꽃의 향기 조향",
    "note": "꽃의 향기 조향",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_048",
    "name": "노란 심장 물상추",
    "listName": "[꽃자수 시간] 노란 심장 물상추",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0200.webp",
    "imageRemote": "https://dorazy.art/images/F0200.webp",
    "acquire": "이벤트 종료",
    "unlock": "꽃자수 시간",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_049",
    "name": "분홍 방울",
    "listName": "[동심 축제] 분홍 방울",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0218.webp",
    "imageRemote": "https://dorazy.art/images/F0218.webp",
    "acquire": "이벤트 종료",
    "unlock": "동심 축제",
    "note": "동심축제 · 2026.05.28 ~ 2026.06.03",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_050",
    "name": "라넌큘러스",
    "listName": "[따스한 봄소풍] 라넌큘러스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0204.webp",
    "imageRemote": "https://dorazy.art/images/F0204.webp",
    "acquire": "이벤트 종료",
    "unlock": "따스한 봄소풍",
    "note": "나른한 시간",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_051",
    "name": "레트로 코코아",
    "listName": "[미식 파티] 레트로 코코아",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0206.webp",
    "imageRemote": "https://dorazy.art/images/F0206.webp",
    "acquire": "이벤트 종료",
    "unlock": "미식 파티",
    "note": "미식 파티 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_052",
    "name": "연분홍 노루귀",
    "listName": "[백화 기록] 연분홍 노루귀",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0240.webp",
    "imageRemote": "https://dorazy.art/images/F0240.webp",
    "acquire": "복각 예정",
    "unlock": "백화 기록",
    "note": "백화기록 / 꽃시장 예정 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_053",
    "name": "금살구 온시디움",
    "listName": "[별똥별의 향기] 금살구 온시디움",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0196.webp",
    "imageRemote": "https://dorazy.art/images/F0196.webp",
    "acquire": "스타소울",
    "unlock": "별똥별의 향기",
    "note": "별똥별의 향기 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_054",
    "name": "순백 코스모스",
    "listName": "[별똥별의 향기] 순백 코스모스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0228.webp",
    "imageRemote": "https://dorazy.art/images/F0228.webp",
    "acquire": "스타소울",
    "unlock": "별똥별의 향기",
    "note": "별똥별의 향기 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_055",
    "name": "연노랑 녹용호",
    "listName": "[별똥별의 향기] 연노랑 녹용호",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0238.webp",
    "imageRemote": "https://dorazy.art/images/F0238.webp",
    "acquire": "스타소울",
    "unlock": "별똥별의 향기",
    "note": "별똥별의 향기 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_056",
    "name": "몬스테라",
    "listName": "[별이슬 드림] 몬스테라",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0208.webp",
    "imageRemote": "https://dorazy.art/images/F0208.webp",
    "acquire": "이벤트 종료",
    "unlock": "별이슬 드림",
    "note": "별이슬 드림",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_057",
    "name": "황금 가시 장미",
    "listName": "[별하늘의 기연] 황금 가시 장미",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0349.webp",
    "imageRemote": "https://dorazy.art/images/F0349.webp",
    "acquire": "이벤트 종료",
    "unlock": "별하늘의 기연",
    "note": "별을 쫓는 달토끼 · 2026.08.15 ~ 2026.08.21",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_058",
    "name": "블루스타 납매",
    "listName": "[빛나는 별의 세계] 블루스타 납매",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0344.webp",
    "imageRemote": "https://dorazy.art/images/F0344.webp",
    "acquire": "카드앨범 · 기간 한정",
    "unlock": "빛나는 별의 세계",
    "note": "빛나는 별의 세계 · 2026.08.10 ~ 2026.09.07",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_059",
    "name": "노란줄무늬 깃털초",
    "listName": "[상방취화] 노란줄무늬 깃털초",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0346.webp",
    "imageRemote": "https://dorazy.art/images/F0346.webp",
    "acquire": "정보 수집 중",
    "unlock": "상방취화",
    "note": "획득 정보 수집 중",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_060",
    "name": "백설 노루귀",
    "listName": "[상방취화] 백설 노루귀",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0210.webp",
    "imageRemote": "https://dorazy.art/images/F0210.webp",
    "acquire": "이벤트 종료",
    "unlock": "상방취화",
    "note": "",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_061",
    "name": "스노우탑 크림슨",
    "listName": "[설산의 기연] 스노우탑 크림슨",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0230.webp",
    "imageRemote": "https://dorazy.art/images/F0230.webp",
    "acquire": "이벤트 종료",
    "unlock": "설산의 기연",
    "note": "아이스 썸머 · 2026.08.01 ~ 2026.08.07",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_062",
    "name": "햇살 맞이 무궁화",
    "listName": "[여름 음악회] 햇살 맞이 무궁화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0256.webp",
    "imageRemote": "https://dorazy.art/images/F0256.webp",
    "acquire": "이벤트 종료",
    "unlock": "여름 음악회",
    "note": "여름 음악회",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_063",
    "name": "송이국화",
    "listName": "[응원 이벤트] 송이국화",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0226.webp",
    "imageRemote": "https://dorazy.art/images/F0226.webp",
    "acquire": "특집 이벤트 · 기간 한정",
    "unlock": "응원 이벤트",
    "note": "응원 이벤트 · 2026.06.04 ~ 2026.09.01 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_064",
    "name": "주사 비단 등불",
    "listName": "[천심 동등] 주사 비단 등불",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0332.webp",
    "imageRemote": "https://dorazy.art/images/F0332.webp",
    "acquire": "이벤트 종료",
    "unlock": "천심 동등",
    "note": "2026.08.06 ~ 2026.08.12 · 꽃티켓 3,888 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_065",
    "name": "눈 솜털 토끼꼬리",
    "listName": "[커플 플라워 데이트] 눈 솜털 토끼꼬리",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0201.webp",
    "imageRemote": "https://dorazy.art/images/F0201.webp",
    "acquire": "이벤트 종료",
    "unlock": "커플 플라워 데이트",
    "note": "2026.07.10 ~ 2026.07.16 · 꽃티켓 3688 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_066",
    "name": "보라색 솜털 토끼꼬리",
    "listName": "[커플 플라워 데이트] 보라색 솜털 토끼꼬리",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0211.webp",
    "imageRemote": "https://dorazy.art/images/F0211.webp",
    "acquire": "이벤트 종료",
    "unlock": "커플 플라워 데이트",
    "note": "",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_067",
    "name": "부드러운 분홍 토끼 꼬리",
    "listName": "[커플 플라워 데이트] 부드러운 분홍 토끼 꼬리",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0217.webp",
    "imageRemote": "https://dorazy.art/images/F0217.webp",
    "acquire": "이벤트 종료",
    "unlock": "커플 플라워 데이트",
    "note": "",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_068",
    "name": "귤빛 불꽃 익소라",
    "listName": "[펫] 귤빛 불꽃 익소라",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0192.webp",
    "imageRemote": "https://dorazy.art/images/F0192.webp",
    "acquire": "기타",
    "unlock": "펫",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_069",
    "name": "이슬에 물든 파란 나비",
    "listName": "[평화로운 우주 질서] 이슬에 물든 파란 나비",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0245.webp",
    "imageRemote": "https://dorazy.art/images/F0245.webp",
    "acquire": "이벤트 종료",
    "unlock": "평화로운 우주 질서",
    "note": "평화로운 우주 질서 · 2026.07.11 ~ 2026.08.08 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_070",
    "name": "진홍빛 석류꽃",
    "listName": "[플로럴 심포니] 진홍빛 석류꽃",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0248.webp",
    "imageRemote": "https://dorazy.art/images/F0248.webp",
    "acquire": "이벤트 종료",
    "unlock": "플로럴 심포니",
    "note": "플로럴 심포니",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_071",
    "name": "앵규다정",
    "listName": "[향기로운 회랑] 앵규다정",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0235.webp",
    "imageRemote": "https://dorazy.art/images/F0235.webp",
    "acquire": "이벤트 종료",
    "unlock": "향기로운 회랑",
    "note": "향기로운 회랑",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_072",
    "name": "눈솜털 안개꽃",
    "listName": "[VIP 상점] 눈솜털 안개꽃",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0202.webp",
    "imageRemote": "https://dorazy.art/images/F0202.webp",
    "acquire": "VIP 상점 종료",
    "unlock": "VIP 상점",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_073",
    "name": "자홍깃 재클린",
    "listName": "[VIP 상점] 자홍깃 재클린",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0246.webp",
    "imageRemote": "https://dorazy.art/images/F0246.webp",
    "acquire": "VIP 상점",
    "unlock": "VIP 상점",
    "note": "옛날 백화점 · 꽃티켓 3888 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_074",
    "name": "푸른 솜털 안개꽃",
    "listName": "[VIP 상점] 푸른 솜털 안개꽃",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0253.webp",
    "imageRemote": "https://dorazy.art/images/F0253.webp",
    "acquire": "VIP 상점 종료",
    "unlock": "VIP 상점",
    "note": "2026.07.01 ~ 2026.07.31 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_075",
    "name": "핑크화이트 시클라멘",
    "listName": "[VIP 상점] 핑크화이트 시클라멘",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0330.webp",
    "imageRemote": "https://dorazy.art/images/F0330.webp",
    "acquire": "VIP 상점 · 기간 한정",
    "unlock": "VIP 상점",
    "note": "2026.08.01 ~ 2026.08.31 · 다이아 168 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_076",
    "name": "발렌타인 황금송이",
    "listName": "[특집 이벤트] 발렌타인 황금송이",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0359.webp",
    "imageRemote": "https://dorazy.art/images/F0359.webp",
    "acquire": "특집 이벤트 · 기간 한정",
    "unlock": "특집 이벤트",
    "note": "백일기념축제 · 2026.08.21 ~ 2026.08.27 · 🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_077",
    "name": "노란 눈의 영광",
    "listName": "[출시 예정] 노란 눈의 영광",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0341.webp",
    "imageRemote": "https://dorazy.art/images/F0341.webp",
    "acquire": "출시 예정",
    "unlock": "출시 예정",
    "note": "🎫 무과금 가능",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_078",
    "name": "쪽빛 플록스",
    "listName": "[출시 예정] 쪽빛 플록스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0250.webp",
    "imageRemote": "https://dorazy.art/images/F0250.webp",
    "acquire": "출시 예정",
    "unlock": "출시 예정",
    "note": "획득 정보 수집 중",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_079",
    "name": "설백 플록스",
    "listName": "[출시 예정] 설백 플록스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0225.webp",
    "imageRemote": "https://dorazy.art/images/F0225.webp",
    "acquire": "출시 예정",
    "unlock": "출시 예정",
    "note": "획득 정보 수집 중",
    "sourceSnapshot": "2026-08-24"
  },
  {
    "id": "R_DEMO_080",
    "name": "분홍 플록스",
    "listName": "[출시 예정] 분홍 플록스",
    "grade": "R",
    "guildScore": 14,
    "image": "https://dorazy.art/images/F0219.webp",
    "imageRemote": "https://dorazy.art/images/F0219.webp",
    "acquire": "출시 예정",
    "unlock": "출시 예정",
    "note": "획득 정보 수집 중",
    "sourceSnapshot": "2026-08-24"
  }
];
