const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-store'
};

async function ensureTable(db) {
  await db.prepare(`
    CREATE TABLE IF NOT EXISTS guild_state (
      id TEXT PRIMARY KEY,
      state_json TEXT NOT NULL,
      updated_at INTEGER NOT NULL
    )
  `).run();
}

function isPlainObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value);
}

function sanitizePatch(input) {
  const patch = {};

  if (Array.isArray(input?.members)) patch.members = input.members;
  if (isPlainObject(input?.checks)) patch.checks = input.checks;
  if (isPlainObject(input?.flowerOptions)) patch.flowerOptions = input.flowerOptions;

  return patch;
}

async function readCurrentState(db, stateId = 'main') {
  const row = await db
    .prepare('SELECT state_json, updated_at FROM guild_state WHERE id = ?1')
    .bind(stateId)
    .first();

  if (!row) return { state: {}, updatedAt: 0, exists: false };

  let state = {};
  try {
    const parsed = JSON.parse(row.state_json);
    if (isPlainObject(parsed)) state = parsed;
  } catch (_) {
    state = {};
  }

  return {
    state,
    updatedAt: Number(row.updated_at || 0),
    exists: true
  };
}

export async function onRequestGet(context) {
  const { env } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const url = new URL(context.request.url);
  const stateId = url.searchParams.get('mode') === 'demo' ? 'demo' : 'main';
  let current = await readCurrentState(env.DB, stateId);

  // 데모 상태가 아직 없으면 운영(main) 상태를 1회 복제해 시작합니다.
  if (stateId === 'demo' && !current.exists) {
    const main = await readCurrentState(env.DB, 'main');
    if (main.exists) {
      const seededAt = Date.now();
      await env.DB.prepare(`
        INSERT INTO guild_state (id, state_json, updated_at)
        VALUES (?1, ?2, ?3)
        ON CONFLICT(id) DO UPDATE SET
          state_json = excluded.state_json,
          updated_at = excluded.updated_at
      `).bind('demo', JSON.stringify(main.state), seededAt).run();
      current = { state: main.state, updatedAt: seededAt, exists: true };
    }
  }

  if (!current.exists) {
    return new Response(JSON.stringify({ exists: false, state: null, updatedAt: 0 }), {
      headers: JSON_HEADERS
    });
  }

  return new Response(JSON.stringify({
    exists: true,
    state: current.state,
    updatedAt: current.updatedAt
  }), { headers: JSON_HEADERS });
}

export async function onRequestPut(context) {
  const { env, request } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  let body;
  try {
    body = await request.json();
  } catch (_) {
    return new Response(JSON.stringify({ error: 'Invalid JSON body.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  const patch = sanitizePatch(body?.state);
  if (Object.keys(patch).length === 0) {
    return new Response(JSON.stringify({ error: 'No valid guild state fields were provided.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const url = new URL(context.request.url);
  const stateId = url.searchParams.get('mode') === 'demo' ? 'demo' : 'main';
  const current = await readCurrentState(env.DB, stateId);
  const mergedState = { ...current.state, ...patch };
  const updatedAt = Date.now();

  await env.DB.prepare(`
    INSERT INTO guild_state (id, state_json, updated_at)
    VALUES (?1, ?2, ?3)
    ON CONFLICT(id) DO UPDATE SET
      state_json = excluded.state_json,
      updated_at = excluded.updated_at
  `).bind(stateId, JSON.stringify(mergedState), updatedAt).run();

  return new Response(JSON.stringify({
    ok: true,
    updatedAt,
    savedFields: Object.keys(patch)
  }), {
    headers: JSON_HEADERS
  });
}



function isValidCheckChange(change) {
  return change && typeof change === 'object'
    && typeof change.key === 'string'
    && change.key.length > 0
    && change.key.length <= 300
    && typeof change.checked === 'boolean';
}

function jsonPathForCheckKey(key) {
  // Checkbox keys are generated by the app and normally contain only
  // grade/index/member-id characters. Escape quotes defensively for JSON path.
  const escaped = key.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `$.checks."${escaped}"`;
}

function isValidOptionChange(change) {
  return change && typeof change === 'object'
    && typeof change.key === 'string'
    && change.key.length > 0
    && change.key.length <= 400
    && Number.isInteger(change.value)
    && change.value >= 0
    && change.value <= 4;
}

function jsonPathForOptionKey(key) {
  const escaped = key.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `$.flowerOptions."${escaped}"`;
}

function isValidMissionChange(change) {
  return change && typeof change === 'object'
    && typeof change.memberId === 'string'
    && change.memberId.length > 0
    && change.memberId.length <= 200
    && typeof change.completed === 'boolean';
}

function jsonPathForMissionMember(memberId) {
  const escaped = memberId.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `$.competitionMissionDone."${escaped}"`;
}

async function ensureStateRow(db, stateId) {
  const now = Date.now();
  await db.prepare(`
    INSERT INTO guild_state (id, state_json, updated_at)
    VALUES (?1, ?2, ?3)
    ON CONFLICT(id) DO NOTHING
  `).bind(stateId, JSON.stringify({ checks: {} }), now).run();
}

export async function onRequestPatch(context) {
  const { env, request } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  let body;
  try {
    body = await request.json();
  } catch (_) {
    return new Response(JSON.stringify({ error: 'Invalid JSON body.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  const changes = Array.isArray(body?.changes)
    ? body.changes.filter(isValidCheckChange)
    : [];

  const optionChanges = Array.isArray(body?.optionChanges)
    ? body.optionChanges.filter(isValidOptionChange)
    : [];

  const missionChanges = Array.isArray(body?.missionChanges)
    ? body.missionChanges.filter(isValidMissionChange)
    : [];

  if ((changes.length === 0 && optionChanges.length === 0 && missionChanges.length === 0) ||
      changes.length > 200 ||
      optionChanges.length > 200 ||
      missionChanges.length > 200 ||
      changes.length + optionChanges.length + missionChanges.length > 250) {
    return new Response(JSON.stringify({ error: 'No valid guild state changes were provided.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const url = new URL(request.url);
  const stateId = url.searchParams.get('mode') === 'demo' ? 'demo' : 'main';

  // Keep the demo seed behavior even if PATCH is the first request.
  if (stateId === 'demo') {
    const demo = await readCurrentState(env.DB, 'demo');
    if (!demo.exists) {
      const main = await readCurrentState(env.DB, 'main');
      if (main.exists) {
        await env.DB.prepare(`
          INSERT INTO guild_state (id, state_json, updated_at)
          VALUES (?1, ?2, ?3)
          ON CONFLICT(id) DO NOTHING
        `).bind('demo', JSON.stringify(main.state), Date.now()).run();
      }
    }
  }

  await ensureStateRow(env.DB, stateId);
  const updatedAt = Date.now();

  const statements = [];

  // Existing checkbox patch behavior.
  changes.forEach(change => {
    const path = jsonPathForCheckKey(change.key);
    if (change.checked) {
      statements.push(env.DB.prepare(`
        UPDATE guild_state
        SET state_json = json_set(
              CASE
                WHEN json_type(state_json, '$.checks') = 'object' THEN state_json
                ELSE json_set(state_json, '$.checks', json('{}'))
              END,
              ?2,
              json('true')
            ),
            updated_at = ?3
        WHERE id = ?1
      `).bind(stateId, path, updatedAt));
      return;
    }

    statements.push(env.DB.prepare(`
      UPDATE guild_state
      SET state_json = json_remove(
            CASE
              WHEN json_type(state_json, '$.checks') = 'object' THEN state_json
              ELSE json_set(state_json, '$.checks', json('{}'))
            END,
            ?2
          ),
          updated_at = ?3
      WHERE id = ?1
    `).bind(stateId, path, updatedAt));
  });

  // Flower option scores are stored sparsely by member + flower.
  // +0 removes the key; +1~+4 stores only the score value.
  optionChanges.forEach(change => {
    const path = jsonPathForOptionKey(change.key);

    if (change.value > 0) {
      statements.push(env.DB.prepare(`
        UPDATE guild_state
        SET state_json = json_set(
              CASE
                WHEN json_type(state_json, '$.flowerOptions') = 'object' THEN state_json
                ELSE json_set(state_json, '$.flowerOptions', json('{}'))
              END,
              ?2,
              ?3
            ),
            updated_at = ?4
        WHERE id = ?1
      `).bind(stateId, path, change.value, updatedAt));
      return;
    }

    statements.push(env.DB.prepare(`
      UPDATE guild_state
      SET state_json = json_remove(
            CASE
              WHEN json_type(state_json, '$.flowerOptions') = 'object' THEN state_json
              ELSE json_set(state_json, '$.flowerOptions', json('{}'))
            END,
            ?2
          ),
          updated_at = ?3
      WHERE id = ?1
    `).bind(stateId, path, updatedAt));
  });

  // Competition mission completion is stored sparsely by member id.
  missionChanges.forEach(change => {
    const path = jsonPathForMissionMember(change.memberId);

    if (change.completed) {
      statements.push(env.DB.prepare(`
        UPDATE guild_state
        SET state_json = json_set(
              CASE
                WHEN json_type(state_json, '$.competitionMissionDone') = 'object' THEN state_json
                ELSE json_set(state_json, '$.competitionMissionDone', json('{}'))
              END,
              ?2,
              json('true')
            ),
            updated_at = ?3
        WHERE id = ?1
      `).bind(stateId, path, updatedAt));
      return;
    }

    statements.push(env.DB.prepare(`
      UPDATE guild_state
      SET state_json = json_remove(
            CASE
              WHEN json_type(state_json, '$.competitionMissionDone') = 'object' THEN state_json
              ELSE json_set(state_json, '$.competitionMissionDone', json('{}'))
            END,
            ?2
          ),
          updated_at = ?3
      WHERE id = ?1
    `).bind(stateId, path, updatedAt));
  });

  await env.DB.batch(statements);

  return new Response(JSON.stringify({
    ok: true,
    updatedAt,
    changedChecks: changes.length,
    changedOptions: optionChanges.length,
    changedMissions: missionChanges.length
  }), { headers: JSON_HEADERS });
}

export async function onRequest(context) {
  if (context.request.method === 'GET') return onRequestGet(context);
  if (context.request.method === 'PUT') return onRequestPut(context);
  if (context.request.method === 'PATCH') return onRequestPatch(context);

  return new Response(JSON.stringify({ error: 'Method not allowed.' }), {
    status: 405,
    headers: { ...JSON_HEADERS, allow: 'GET, PUT, PATCH' }
  });
}
