const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-store'
};

async function ensureTable(db) {
  await db.prepare(`
    CREATE TABLE IF NOT EXISTS guild_state (
      id TEXT PRIMARY KEY,
      state_json TEXT NOT NULL,
      updated_at INTEGER NOT NULL
    )
  `).run();
}

function isPlainObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value);
}

function sanitizePatch(input) {
  const patch = {};

  if (Array.isArray(input?.members)) patch.members = input.members;
  if (isPlainObject(input?.checks)) patch.checks = input.checks;
  if (Array.isArray(input?.customFlowers)) patch.customFlowers = input.customFlowers;
  if (Array.isArray(input?.updateList)) patch.updateList = input.updateList;

  return patch;
}

async function readCurrentState(db) {
  const row = await db
    .prepare('SELECT state_json, updated_at FROM guild_state WHERE id = ?1')
    .bind('main')
    .first();

  if (!row) return { state: {}, updatedAt: 0, exists: false };

  let state = {};
  try {
    const parsed = JSON.parse(row.state_json);
    if (isPlainObject(parsed)) state = parsed;
  } catch (_) {
    state = {};
  }

  return {
    state,
    updatedAt: Number(row.updated_at || 0),
    exists: true
  };
}

export async function onRequestGet(context) {
  const { env } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const current = await readCurrentState(env.DB);

  if (!current.exists) {
    return new Response(JSON.stringify({ exists: false, state: null, updatedAt: 0 }), {
      headers: JSON_HEADERS
    });
  }

  return new Response(JSON.stringify({
    exists: true,
    state: current.state,
    updatedAt: current.updatedAt
  }), { headers: JSON_HEADERS });
}

export async function onRequestPut(context) {
  const { env, request } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  let body;
  try {
    body = await request.json();
  } catch (_) {
    return new Response(JSON.stringify({ error: 'Invalid JSON body.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  const patch = sanitizePatch(body?.state);
  if (Object.keys(patch).length === 0) {
    return new Response(JSON.stringify({ error: 'No valid guild state fields were provided.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const current = await readCurrentState(env.DB);
  const mergedState = { ...current.state, ...patch };
  const updatedAt = Date.now();

  await env.DB.prepare(`
    INSERT INTO guild_state (id, state_json, updated_at)
    VALUES (?1, ?2, ?3)
    ON CONFLICT(id) DO UPDATE SET
      state_json = excluded.state_json,
      updated_at = excluded.updated_at
  `).bind('main', JSON.stringify(mergedState), updatedAt).run();

  return new Response(JSON.stringify({
    ok: true,
    updatedAt,
    savedFields: Object.keys(patch)
  }), {
    headers: JSON_HEADERS
  });
}

function isValidCheckChange(change) {
  return change && typeof change === 'object'
    && typeof change.key === 'string'
    && change.key.length > 0
    && change.key.length <= 300
    && typeof change.checked === 'boolean';
}

function jsonPathForCheckKey(key) {
  // Checkbox keys are generated by the app and normally contain only
  // grade/index/member-id characters. Escape quotes defensively for JSON path.
  const escaped = key.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `$.checks."${escaped}"`;
}

async function ensureStateRow(db, stateId) {
  const now = Date.now();
  await db.prepare(`
    INSERT INTO guild_state (id, state_json, updated_at)
    VALUES (?1, ?2, ?3)
    ON CONFLICT(id) DO NOTHING
  `).bind(stateId, JSON.stringify({ checks: {} }), now).run();
}

export async function onRequestPatch(context) {
  const { env, request } = context;
  if (!env.DB) {
    return new Response(JSON.stringify({ error: 'D1 binding DB is not configured.' }), {
      status: 500,
      headers: JSON_HEADERS
    });
  }

  let body;
  try {
    body = await request.json();
  } catch (_) {
    return new Response(JSON.stringify({ error: 'Invalid JSON body.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  const changes = Array.isArray(body?.changes)
    ? body.changes.filter(isValidCheckChange)
    : [];

  if (changes.length === 0 || changes.length > 200) {
    return new Response(JSON.stringify({ error: 'No valid checkbox changes were provided.' }), {
      status: 400,
      headers: JSON_HEADERS
    });
  }

  await ensureTable(env.DB);
  const stateId = 'main';

  await ensureStateRow(env.DB, stateId);
  const updatedAt = Date.now();

  // Each checkbox is patched inside the JSON document with SQL itself instead
  // of replacing the whole checks object. This prevents two browsers from
  // overwriting each other's recent checkbox edits.
  const statements = changes.map(change => {
    const path = jsonPathForCheckKey(change.key);
    if (change.checked) {
      return env.DB.prepare(`
        UPDATE guild_state
        SET state_json = json_set(
              CASE
                WHEN json_type(state_json, '$.checks') = 'object' THEN state_json
                ELSE json_set(state_json, '$.checks', json('{}'))
              END,
              ?2,
              json('true')
            ),
            updated_at = ?3
        WHERE id = ?1
      `).bind(stateId, path, updatedAt);
    }

    return env.DB.prepare(`
      UPDATE guild_state
      SET state_json = json_remove(
            CASE
              WHEN json_type(state_json, '$.checks') = 'object' THEN state_json
              ELSE json_set(state_json, '$.checks', json('{}'))
            END,
            ?2
          ),
          updated_at = ?3
      WHERE id = ?1
    `).bind(stateId, path, updatedAt);
  });

  await env.DB.batch(statements);

  return new Response(JSON.stringify({
    ok: true,
    updatedAt,
    changed: changes.length
  }), { headers: JSON_HEADERS });
}

export async function onRequest(context) {
  if (context.request.method === 'GET') return onRequestGet(context);
  if (context.request.method === 'PUT') return onRequestPut(context);
  if (context.request.method === 'PATCH') return onRequestPatch(context);

  return new Response(JSON.stringify({ error: 'Method not allowed.' }), {
    status: 405,
    headers: { ...JSON_HEADERS, allow: 'GET, PUT, PATCH' }
  });
}
